## Notebook 3.2: Introduction to Numpy

This notebook is associated with the following accompanied reading: 

+ Yandell, Mark, and Daniel Ence. 2012. “A Beginner’s Guide to Eukaryotic Genome Annotation.” Nature Reviews Genetics 13 (5): 329–42. https://doi.org/10.1038/nrg3174.


+ The Python Data Science Handbook **Chapter 2** https://jakevdp.github.io/PythonDataScienceHandbook/


## Learning objectives: 

By the end of this module you should be able to:

1. Find and use scientific and numerical functions in `numpy`.
2. Generate arrays of data and compute values on them. 
3. Understand the difference between lists and numpy arrays.
4. Calculate N50 contig size. 


## Introduction to numpy

This notebook should be completed while reading Chapter 2 of the Data Science Handbook that was assigned for your reading. The numpy library is a *third party* Python library, meaning that it is not distributed by default with every Python installation. It can be easily installed however, and provides a huge suite of tools for scientific computing. I think that the assigned Chapter introduces numpy very well, so this notebook will mostly consist of exercises to test your comprehension of the reading. 

In [195]:
# start by importing numpy 
import numpy as np


### Create a numpy array
There are many ways to create a numpy array. Numpy has several built-in functions for generating arrays that are composed entirely of one value, or a range of values using `.zeros()`, `.ones()`, or `.arange()`; or, we can also generate an array by passing in a list like in the last two examples below. 

In [196]:
# create an array with ten items in it that are all zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [197]:
# create an array with ten items that are all zeros as integers
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [198]:
# create an array with a range of values from 0-10
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [199]:
# create an array from a list
np.array([0, 3, 4, 10, 2, 2, 2, 2])

array([ 0,  3,  4, 10,  2,  2,  2,  2])

In [200]:
# create an array that is made of 0 and 1 alternating
np.array([0, 1] * 5)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

### However, the datatype is important... 
When you create a numpy array from a list it tries to infer the datatype from contents of the list. Above, when we created a list of all int elements it created an int array. However, when we pass it a list below where some elements are ints and some are strings, it converts everything to strings. **This is because numpy works most efficiently by storing all data in an array as a single datatype**. You can create arrays with a mixed datatype but you lose much of the efficiency of numpy when you do so. 

In [201]:
# mixed type lists will be converted to a single dtype array
np.array([0, 1, "apple", "orange"])

array(['0', '1', 'apple', 'orange'], dtype='<U21')

## Dimensions and indexing

Numpy arrays can be indexed just like Python list objects to select particular elements from them. In addition to the one dimension in which lists can be indexed, however, arrays can be indexed in multiple dimensions to select both rows and columns, and they can apply functions over these indices as well. If you need a refresher on how to `index` and `slice` objects in Python look back at our reading from last week ([link](https://docs.python.org/3/tutorial/introduction.html)), or google "python indexing". 

In [202]:
# create a 2-dimensional array 
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [203]:
# create a 3-dimensional array
np.zeros((5, 3, 3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [204]:
# index the third element in a 1-d array
np.arange(100)[3]

3

In [205]:
# slice the third through tenth elements in a 1-d array
np.arange(100)[3:10]

array([3, 4, 5, 6, 7, 8, 9])

### Testing your skills

<div class="alert alert-success">
    <b>Action [5]:</b> 
    Create a 2-dimensional array with 3 rows and 5 columns that is composed entirely of cells with the integer value 35. 
</div>

In [209]:
np.full((3, 5), 35)

array([[35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35]])

<div class="alert alert-success">
    <b>Action [6]:</b> 
    Create a 2-dimensional array of size (3, 5) that is composed of random integers generated by numpy.
</div>

In [211]:
np.random.randint(0, 100, size=(3, 5))

array([[33, 55, 90, 20, 62],
       [84,  7, 99, 12, 30],
       [41, 28, 54,  2, 11]])

<div class="alert alert-success">
    <b>Action [7]:</b> 
    Return the values [24, 25, 26] from the array below by using slicing. 
</div>

In [215]:
arr = np.arange(40)
arr[24:27]

array([24, 25, 26])

<div class="alert alert-success">
    <b>Action [8]:</b> 
    Return the values [14, 16, 18, 20, 22] from the array below by slicing. 
</div>

In [219]:
arr = np.arange(24).reshape((12, 2))
arr[7:, 0]

array([14, 16, 18, 20, 22])

## Filling an array with data

When learning about lists and dictionaries we learned that a convenient way to use these objects is to first create an empty list or dictionary and then fill it with values as you iterate over some process and append items to the list, or add new key/val pairs to the dictionary. In numpy you have to do things a bit differently. You start by creating an array that is the full size that you plan to work, initialized with some null value like zeros, and then you update the values with new data. 

The difference between these two approaches may seem subtle, but it can lead to huge speed improvements when done correctly in numpy. This is because numpy essentially reserves space in your computers memory for the size of the `array`, whereas a `list` that changes size as you extend it will need to keep updating the object in memory. As explained in your reading, this allows numpy to perform calculations using compiled functions in faster languages like C and fortran; it's a workaround that allows us to write pretty Python code but still benefit from super fast speed. 

These details only begin to matter when you do pretty high level computing, but it's worth learning the motivation for why we use numpy, and why the code looks the way that it does.  

In [220]:
# good practice with lists: start with an empty list and fill it as you iterate
empty = []
for i in range(100):
    empty.append(i)

In [221]:
# filling an empty array doesn't work like with lists
empty = np.array([])
for i in range(100):
    # ... a function does not exist to extend the size of arrays.
    # ... only to generate new arrays of a given size
    pass

In [222]:
# instead, you create the full sized array with null values and update them by indexing
empty = np.zeros(100)
for i in range(100):
    empty[i] = i

## Biological examples


<div class="alert alert-success">
    <b>Question [9]:</b> 
In your reading by Yandell and Ence they describe the use of summary statistics for describing the completeness and contiguity of a genome assembly. In Box 1 this includes a description of the N50 statistic. Using Markdown explain what an N50 contig size, and an N50 scaffold size. Is  bigger or smaller N50 better?

</div>

N50 contig or scaffold size is a statistic to describe the completeness of a genome assembly. Larger values mean that the genome is assembled and ordered into larger contiguous sequences. The statistic is calculated by ordering all contigs (or scaffolds) in a list by their length and calculating the running sum until it equals one-half of the total length of all contigs (or scaffolds). The length of the smallest contig (or scaffold) in this list is the N50 size. 

### Computing N50 with numpy 

<div class="alert alert-success">
    <b>Action [10]:</b> 
Insert short comments at the indicated positions in the 10 code cells below to describe what each chunk of code is doing. Hint: Look at the document string of each function interactively by putting your cursor inside of the parentheses and holding shift and pressing tab; Look in your assigned Chapter 2 reading; google the function name; and try to infer based on the returned output and the name of the function.
</div>

In [ ]:
# 1. comment: generate random ints between 1000-50000 to represent contig lengths
contig_sizes = np.random.randint(1000, 50000, size=50)
contig_sizes

In [ ]:
# 2. comment: sort the ints in the array 
contig_sizes.sort()
contig_sizes

In [ ]:
# 3. comment: reverse the sorted order
contig_sizes = contig_sizes[::-1]
contig_sizes

In [ ]:
# 4. comment: calculate the total length of all contigs
total_len = contig_sizes.sum()
total_len

In [ ]:
# 5. comment: get half the total contig length
half_total_len = total_len / 2
half_total_len

In [ ]:
# 6. comment: create an array of zeros of the length of the number of contigs
contig_sum_lens = np.zeros(contig_sizes.size, dtype=int)
contig_sum_lens

In [250]:
# 7. comment: iterate over the sorted contigs summing each 
for i in range(contig_sizes.size):
    contig_sum_lens[i] = contig_sizes[i:].sum()
contig_sum_lens

array([1231162, 1181930, 1133818, 1087286, 1041273,  995845,  950544,
        905331,  860899,  816550,  773146,  730936,  689744,  649924,
        614539,  579406,  544563,  510383,  477916,  447132,  416423,
        389729,  364178,  338966,  313998,  289842,  266850,  243988,
        221985,  200160,  182073,  164613,  147382,  130256,  113580,
         97946,   83351,   70549,   58527,   49658,   42035,   34822,
         28480,   23074,   17874,   13049,    9154,    5846,    2727,
          1329])

In [251]:
# 8. comment: get boolean for whether sum is greater than half the total
which_contigs_longer_than_half = contig_sum_lens > half_total_len
which_contigs_longer_than_half

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [254]:
# 9. comment: get the value of the True values (greater than half)
contigs_longer_than_half = contig_sizes[which_contigs_longer_than_half]
contigs_longer_than_half

array([49232, 48112, 46532, 46013, 45428, 45301, 45213, 44432, 44349,
       43404, 42210, 41192, 39820, 35385])

In [256]:
# 10. comment: get the contig length of the smallest contig with summed len < half total
n50 = contigs_longer_than_half.min()
n50

35385

<div class="alert alert-success">
    <b>Question [11]:</b> 
Summarize in Markdown below how the ten lines of code above accomplish the task of computing N50 starting with a list of contig lengths. 
</div>

The code above uses numpy arrays to generate a random list of contig lengths and then to compute the N50 of those lengths. It does this by calculting half the sum of the total lengths as the target value. Then it sums ordered runs of contig lengths using slicing and finds which contig length is the first to have an ordered sum that is greater than half the total contig lengths.  

<div class="alert alert-success">
    <b>Action [12]:</b> 
Bonus challenge: combine th lines of code above together into a function that takes the list of contig lengths as an input argument and returns the N50 statistic. Test your function to see if it works. If you get stuck on this do not worry.  
</div>

In [278]:
# I wrote this answer to sum from the beginning rather than the end as before;
# summing from either end works equally, you can define N50 either way since 
# it only depends on *where* the sum equals half.

def calculate_N50(contig_sizes):
    
    # sort contigs
    contig_sizes.sort()
    contig_sizes = contig_sizes[::-1]
    
    # get target length
    half_total_len = contig_sizes.sum() / 2
    
    # fill array with running sums (increasing)
    contig_sum_lens = np.zeros(contig_sizes.size, dtype=int)
    for i in range(contig_sizes.size):
        contig_sum_lens[i] = contig_sizes[:i+1].sum()
        
    # get boolean for whether sum is greater than half the total
    which_contigs_longer_than_half = contig_sum_lens > half_total_len

    # index contig with that len
    n50 = contig_sizes[which_contigs_longer_than_half].max()
    
    return n50

In [279]:
calculate_N50(contig_sizes)

35385

<div class="alert alert-success">
    <b>Action:</b> 
Save and Download this notebook as HTML to upload to courseworks.
</div>